package pluginmgr

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
)

const generatedFileName = "imports_gen.go"

const generatedHeader = `// Code generated by "beelzebub plugin". DO NOT EDIT.
//
// This file blank-imports every installed plugin so that each plugin's init()
// runs and registers it with pkg/plugin. Regenerated on every install/remove.

package plugins
`

func renderImports(importPaths []string) ([]byte, error) {
	seen := make(map[string]struct{}, len(importPaths))
	uniq := make([]string, 0, len(importPaths))
	for _, p := range importPaths {
		if p == "" {
			continue
		}
		if _, ok := seen[p]; ok {
			continue
		}
		seen[p] = struct{}{}
		uniq = append(uniq, p)
	}
	sort.Strings(uniq)

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	if len(uniq) > 0 {
		buf.WriteString("\nimport (\n")
		for _, p := range uniq {
			fmt.Fprintf(&buf, "\t_ %q\n", p)
		}
		buf.WriteString(")\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated imports: %w", err)
	}
	return formatted, nil
}

func writeImportsFile(pluginsDir string, lf *LockFile) error {
	paths := make([]string, 0, len(lf.Plugins))
	for _, p := range lf.Plugins {
		paths = append(paths, p.Import)
	}
	src, err := renderImports(paths)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(pluginsDir, 0o755); err != nil {
		return fmt.Errorf("creating plugins dir: %w", err)
	}
	dst := filepath.Join(pluginsDir, generatedFileName)
	if err := os.WriteFile(dst, src, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", dst, err)
	}
	return nil
}
