// Code generated by "beelzebub plugin". DO NOT EDIT.
//
// This file blank-imports every installed plugin so that each plugin's init()
// runs and registers it with pkg/plugin. Regenerated on every install/remove.

package plugins
